
const motivateMe = () => {
    let firstPhrase = ['All our dreams can come true, if we have the courage to pursue them.', 'Only the paranoid survive.', 'Everything you can imagine is real.', 'Smart people learn from everything and everyone, average people from their experiences, stupid people already have all the answers.', 'Whatever you are, be a good one.', 'Your passion is waiting for your courage to catch up.', 'Magic is believing in yourself. If you can make that happen, you can make anything happen.', 'If something is important enough, even if the odds are stacked against you, you should still do it.', 'If you believe it’ll work out, you’ll see opportunities. If you don’t believe it’ll work out, you’ll see obstacles.', 'If opportunity doesn’t knock, build a door.', 'Hard work beats talent when talent doesn’t work hard.', 'The best way to appreciate your job is to imagine yourself without one.', 'Work hard, be kind, and amazing things will happen.', 'Sometimes when you’re in a dark place you think you’ve been buried but you’ve actually been planted.', 'When written in Chinese the word “crisis” is composed of two characters – one represents danger and the other represents opportunity.', 'Start where you are. Use what you have. Do what you can.', 'Go the extra mile. It’s never crowded there.', 'H.O.P.E. = Hold On. Pain Ends.', 'Wherever you go, go with all your heart', 'Opportunities don’t happen. You create them.', 'Never regret anything that made you smile.', 'Doubt kills more dreams than failure ever will.', 'Focus on being productive instead of busy.', 'When someone says you can’t do it, do it twice and take pictures.', 'If you’re too comfortable, it’s time to move on. Terrified of what’s next? You’re on the right track.', 'Don’t compare yourself to others. Be like the sun and the moon and shine when it’s your time.', 'Be so good they can’t ignore you.', 'If you don’t get out of the box you’ve been raised in, you won’t understand how much bigger the world is.', 'Do what you can, with what you have, where you are.', 'Trust yourself that you can do it and get it.'];
    let secondPhrase = ['The secret of getting ahead is getting started.', 'It’s hard to beat a person who never gives up.', 'Do one thing every day that scares you.', 'Do what you feel in your heart to be right – for you’ll be criticized anyway.', 'You can either experience the pain of discipline or the pain of regret. The choice is yours.', 'Hold the vision, trust the process.', 'Don’t be afraid to give up the good to go for the great.', 'No one is to blame for your future situation but yourself. If you want to be successful, then become successful.', 'Invest in your dreams. Grind now. Shine later.', 'We are what we repeatedly do. Excellence, then, is not an act, but a habit.', 'In a gentle way, you can shake the world.', 'Work hard in silence, let your success be the noise.', 'Opportunity is missed by most people because it is dressed in overalls and looks like work.', 'Never stop doing your best just because someone doesn’t give you credit.', 'Don’t limit your challenges. Challenge your limits.', 'Don’t quit yet, the worst moments are usually followed by the most beautiful silver linings. You have to stay strong, remember to keep your head up and remain hopeful.', 'In the middle of every difficulty lies opportunity.', 'Keep your face always toward the sunshine – and shadows will fall behind you.', 'Turn your wounds into wisdom', 'Begin anywhere.', 'Success is liking yourself, liking what you do, and liking how you do it.', 'You must do the thing you think you cannot do.', 'I never lose. Either I win or learn.', 'You don’t need to see the whole staircase, just take the first step.', 'I didn’t get there by wishing for it, but by working for it.', 'Sunshine all the time makes a desert.', 'You’re so much stronger than your excuses', 'Don’t Quit', 'Nothing can dim the light that shines from within.', 'Take criticism seriously, but not personally. If there is truth or merit in the criticism, try to learn from it. Otherwise, let it roll right off you.', 'It’s never too late to be what you might’ve been.'];
    let thirdPhrase = ['The best time to plant a tree was 20 years ago. The second best time is now.', 'If people are doubting how far you can go, go so far that you can’t hear them anymore.', 'It’s no use going back to yesterday, because I was a different person then.', 'Happiness is not something ready made. It comes from your own actions.', 'Impossible is just an opinion.', 'Great things are done by a series of small things brought together', 'Very often, a change of self is needed more than a change of scene.', 'It’s not the load that breaks you down, it’s the way you carry it.', 'The hard days are what make you stronger.', 'Keep your eyes on the stars, and your feet on the ground.', 'You’ve got to get up every morning with determination if you’re going to go to bed with satisfaction.', 'The only difference between ordinary and extraordinary is that little extra.', 'Unsuccessful people make their decisions based on their current situations. Successful people make their decisions based on where they want to be.', 'Whenever you find yourself doubting how far you can go, just remember how far you have come.', 'Good. Better. Best. Never let it rest. ‘Til your good is better and your better is best.', 'Dreams don’t work unless you do.', 'What defines us is how well we rise after falling.', 'Make each day your masterpiece.', 'We can do anything we want to if we stick to it long enough.', 'You can cry, scream, and bang your head in frustration but keep pushing forward. It’s worth it.', 'Today is your opportunity to build the tomorrow you want.', 'It’s not all sunshine and rainbows, but a good amount of it actually is.', 'Be happy with what you have while working for what you want.', 'The big lesson in life is never be scared of anyone or anything.', 'Don’t tell everyone your plans, instead show them your results.', 'This is a reminder to you to create your own rule book, and live your life the way you want it.', 'Do the best you can. No one can do more than that.', 'If you can dream it, you can do it.']

    let randomNumberOne = Math.floor(Math.random() * firstPhrase.length);
    let randomNumberTwo= Math.floor(Math.random() * secondPhrase.length);
    let randomNumberThree = Math.floor(Math.random() * thirdPhrase.length);
   
    return firstPhrase[randomNumberOne] + '\n' + secondPhrase[randomNumberTwo] + '\n' + thirdPhrase[randomNumberThree];
}

console.log(motivateMe());